### ISSUE TITLE
Travis YAML

### ISSUE THREAD

**Issue by coursar** [foxslot/JS_HW10_PostsWebpack#2]
https://github.com/foxslot/JS_HW10_PostsWebpack/blob/05fecbb1644527ed1a9951d8ca7471ccf497a0d5/.travis.yml#L4-L11

`on` должно быть в `deploy`:
```yaml
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
```
